ARG DOCKER_HUB_PREFIX=optomistic_tanuki
ARG BASE_IMAGE_TAG=latest
# Use the base Dockerfile from the root of the project
FROM ${DOCKER_HUB_PREFIX-}/optomistic_tanuki_base:${BASE_IMAGE_TAG} AS builder

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .


# Build the authentication service
RUN npx nx build authentication

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/authentication /app/dist/apps/authentication
COPY --from=builder /app/node_modules /app/node_modules

# Start the application
CMD ["node", "/app/dist/apps/authentication/main.js"]