FROM optomistic_tanuki/base:latest AS builder

WORKDIR /app    

COPY . .

RUN npx nx build social

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/social /app/dist/apps/social
COPY --from=builder /app/node_modules /app/node_modules

CMD ["node", "/app/dist/apps/social/main.js"]