networks:
  ot_network:
    driver: bridge
x-global-environment: &x-global-environment
  environment:
    NX_DAEMON_DISABLE: true

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./defaultnginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - ot_network
    depends_on:
      - ot_client_interface
      - ot_gateway
  build_base:
    image: optomistic_tanuki_base
    env_file:
      - .env
    build:
      dockerfile: ./dockerfile
      context: .
    command: ["sh", "-c", "exit 0"]
    networks:
      - ot_network
    restart: "no"
  migration_runner:
    image: optomistic_tanuki_base
    depends_on:
      - build_base
      - db
      - db_init
    env_file:
      - .env
    entrypoint: [ "sh", "/app/run-migrations.sh"]
    volumes:
      - ./apps/authentication/src/assets/config.yaml:/app/apps/authentication/src/assets/config.yaml
      - ./apps/profile/src/assets/config.yaml:/app/apps/profile/src/assets/config.yaml
      - ./apps/social/src/assets/config.yaml:/app/apps/social/src/assets/config.yaml
      - ./apps/tasks/src/assets/config.yaml:/app/apps/tasks/src/assets/config.yaml
    networks:
      - ot_network
    restart: "no"
  db_init:
    image: postgres:latest
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ADDITIONAL_DBS: ${ADDITIONAL_DBS}
    entrypoint: ["sh", "/app/create-dbs.sh"]
    restart: "no"
    volumes:
      - ./create-dbs.sh:/app/create-dbs.sh
      - ./.env:/app/.env
    networks:
      - ot_network
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - ot_network
  ot_client_interface:
    container_name: ot_client_interface
    # image: optomistic_tanuki_client_interface
    command: ["sh", "-c", "npx nx run client-interface:serve:development --host=0.0.0.0 --port=80"]
    build:
      dockerfile: ./apps/client-interface/dockerfile.dev
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
    networks:
      - ot_network
    volumes:
      - ./:/app/
    ports:
      - 4200:4200
      - 5000:5000
    <<: *x-global-environment
  ot_authentication:
    container_name: ot_authentication
    # image: optomistic_tanuki_authentication
    build:
      dockerfile: ./apps/authentication/dockerfile
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
    networks:
      - ot_network
    volumes:
      - ./:/app/
    command: ["sh", "-c", "npx nx serve authentication"]
    <<: *x-global-environment
  ot_gateway:
    container_name: ot_gateway
    # image: optomistic_tanuki_gateway
    build:
      dockerfile: ./apps/gateway/dockerfile
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
      - ot_authentication
      - ot_profile
      - ot_social
      - ot_tasks
    networks:
      - ot_network
    volumes:
      - ./:/app/
    command: ["sh", "-c", "npx nx serve gateway"]
    ports:
      - 3000:3000
    <<: *x-global-environment
  ot_profile:
    container_name: ot_profile
    # image: optomistic_tanuki_profile
    build:
      dockerfile: ./apps/profile/dockerfile
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
    networks:
      - ot_network
    volumes:
      - ./:/app/
    command: ["sh", "-c", "npx nx serve profile"]
    <<: *x-global-environment
  ot_social:
    container_name: ot_social
    # image: optomistic_tanuki_social
    build:
      dockerfile: ./apps/social/dockerfile
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
    networks:
      - ot_network
    volumes:
      - ./:/app/
    command: ["sh", "-c", "npx nx serve social"]
    <<: *x-global-environment
  ot_tasks:
    container_name: ot_tasks
    # image: optomistic_tanuki_tasks
    build:
      dockerfile: ./apps/tasks/dockerfile
      context: .
    depends_on:
      - build_base
      - db
      - migration_runner
    networks:
      - ot_network
    volumes:
      - ./:/app/
    command: ["sh", "-c", "npx nx serve tasks"]
    <<: *x-global-environment
