const ServiceTokens = {
    AUTHENTICATION_SERVICE: 'AUTHENTICATION_SERVICE',
    PROFILE_SERVICE: 'PROFILE_SERVICE',
    SOCIAL_SERVICE: 'SOCIAL_SERVICE',
    TASKS_SERVICE: 'TASKS_SERVICE',
}
export { ServiceTokens }