FROM optomistic_tanuki/base:latest AS builder

WORKDIR /app

COPY . .

RUN npx nx build gateway

FROM node:lts-bookworm-slim

WORKDIR /app

COPY --from=builder /app/dist/apps/gateway /app/dist/apps/gateway
COPY --from=builder /app/node_modules /app/node_modules

CMD ["node", "/app/dist/apps/gateway/main.js"]