ARG DOCKER_HUB_PREFIX=optomistic_tanuki
ARG BASE_IMAGE_TAG=latest
FROM ${DOCKER_HUB_PREFIX-}/optomistic_tanuki_base:${BASE_IMAGE_TAG} AS builder

WORKDIR /app

COPY . .

RUN npx nx build gateway

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/gateway /app/dist/apps/gateway
COPY --from=builder /app/node_modules /app/node_modules

CMD ["node", "/app/dist/apps/gateway/main.js"]