# Use the base image
FROM optomistic_tanuki/base AS build

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npx nx build client-interface --verbose

# Use a lightweight Node.js image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Install serve globally
RUN npm install -g serve

# Copy the built Angular application
COPY --from=build /app/dist/apps/client-interface /app

# Expose port 4200
EXPOSE 4200

# Start the application using serve
CMD ["serve", "-s", ".", "-l", "0.0.0.0:4200"]
