ARG DOCKER_HUB_PREFIX=optomistic_tanuki
ARG BASE_IMAGE_TAG=latest
# Use the base image
FROM ${DOCKER_HUB_PREFIX-}/optomistic_tanuki_base:${BASE_IMAGE_TAG} AS build

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npx nx build client-interface --verbose

# FROM nginx:latest
# Use a lightweight Node.js image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Install serve globally
RUN npm install -g serve

# Copy the built Angular application
# COPY --from=build /app/dist/apps/client-interface /usr/share/nginx/html
COPY --from=build /app/dist/apps/client-interface/browser /app

# Expose port 4200
EXPOSE 80

# Start the application using serve
# CMD ["nginx", "-g", "daemon off;" ]
CMD ["serve", "-s", ".", "-l", "80"]
