# Use the base image
FROM node:lts-alpine

ENV NX_DAEMON_DISABLE=true

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

RUN npm i && npm i -g nx@latest

# Build the Angular application
RUN npx nx build client-interface --verbose

